# Overview of the Workshop {.unnumbered}

There are four sections to this workshop:

- [Chapter 1](01-basics.qmd): The Basics of SPSS
- [Chapter 2](02-variables.qmd): Working with Variables
- [Chapter 3](03-data-management.qmd): Understanding Data Management Tasks
- [Chapter 4](04-stats.qmd): Understanding Graphical & Statistical Procedures,
  Msc.

These sections will generally be presented in sequence. The discussion will
alternate between theory and practice. The format will alternate between lecture
and lab sessions. Please ask questions as soon as they arise in your mind.
Please provide feedback or voice concerns.

There is additionally an [Appendix](appendix.qmd) which primarily houses the
exercise solutions, as well as a collection of additional, more advanced,
exercises.

## Contact information {.unnumbered}

### CSCAR {.unnumbered}

- Office Hours: Monday-Friday 9am to 5pm (Closed Tuesday 12-1pm)
- Phone: 734.764.7828
- Statistical Assistance: stats-consulting@umich.edu
- Data Science Assistance: ds-consulting@umich.edu
- High Performance Computing: hpc-consulting@umich.edu
- <http://cscar.research.umich.edu/>

## Acknowledgments {.unnumbered}

These notes have evolved over the years thanks to many CSCAR
statisticians, including Corey Powell, Josh Errickson, Giselle
Kolenic, and Missy Plegue.

This material was created for use in workshops and short courses
presented by faculty and staff from the Consulting for Statistics,
Computing \& Analytics Research (CSCAR) at the University of
Michigan. No part of this material may be used for other purposes,
copied, changed, or sold.

## Images {.unnumbered}

All images embedded within the document should link to a full-size version of
the image.

## Data {.unnumbered}

There are a number of data sets used in these notes; some used for the examples,
others for the execises.

[data.zip](https://github.com/CSCAR/workshop-spss/raw/master/data/data.zip) -
This zip files contains all data used within the notes.

### Example Data {.unnumbered}

- Section 2:
  [section2_data.sav](https://github.com/CSCAR/workshop-spss/raw/master/data/section3_data.sav)
- Section 3:
  [section3_data.sav](https://github.com/CSCAR/workshop-spss/raw/master/data/section4_data.sav)
- Section 4:
  [section4_1_data.sav](https://github.com/CSCAR/workshop-spss/raw/master/data/section5_1_data.sav),
  [section4_2_data.sav](https://github.com/CSCAR/workshop-spss/raw/master/data/section5_2_data.sav)

### Exercise Data {.unnumbered}

- Exercise 0:
[exercise0_data.sav](https://github.com/CSCAR/workshop-spss/raw/master/data/exercise0/exercise0_data.sav),
[exercise0_output.spv](https://github.com/CSCAR/workshop-spss/raw/master/data/exercise0/exercise0_output.spv),
[exercise0_syntax.sps](https://github.com/CSCAR/workshop-spss/raw/master/data/exercise0/exercise0_syntax.sps)
(You may need to right-click \& Save As for the .sps file)
- Exercise 1:
  [exercise1_data.sav](https://github.com/CSCAR/workshop-spss/raw/master/data/exercise1/exercise1_data.sav)
- Exercise 2:
  [exercise2_data.xls](https://github.com/CSCAR/workshop-spss/raw/master/data/exercise2/exercise2_data.xls)
- Exercise 3:
  [exercise3_data.sav](https://github.com/CSCAR/workshop-spss/raw/master/data/exercise3/exercise3_data.sav)
- Exercise 4:
  [exercise4_data.sav](https://github.com/CSCAR/workshop-spss/raw/master/data/exercise4/exercise4_data.sav)
- Exercise 5:
  [exercise5_data.sav](https://github.com/CSCAR/workshop-spss/raw/master/data/exercise5/exercise5_data.sav)
- Exercise 6:
  [exercise6_data.sav](https://github.com/CSCAR/workshop-spss/raw/master/data/exercise6/exercise6_data.sav)
- Exercise 7:
  [exercise7_data.sav](https://github.com/CSCAR/workshop-spss/raw/master/data/exercise7/exercise7_data.sav)
- Exercise 8:
  [exercise8_data.sav](https://github.com/CSCAR/workshop-spss/raw/master/data/exercise8/exercise8_data.sav)

### Additional Exercises {.unnumbered}

These are for the [additional exercises](appendix.qmd#additional-exercises) and
[final project](appendix.qmd#final-project) found in the appendix.

- Exercise A1:
  [exercisea1_data.sav](https://github.com/CSCAR/workshop-spss/raw/master/data/exercisea1/exercisea1_data.sav)
- Exercise A2:
  [exercisea2_data.sav](https://github.com/CSCAR/workshop-spss/raw/master/data/exercisea2/exercisea2_data.sav)
- Exercise A3:
[exercisea3_data_a.sav](https://github.com/CSCAR/workshop-spss/raw/master/data/exercisea3/exercisea3_data_a.sav),
[exercisea3_data_b.sav](https://github.com/CSCAR/workshop-spss/raw/master/data/exercisea3/exercisea3_data_b.sav)
- Exercise A4:
  [exercisea4_data.sav](https://github.com/CSCAR/workshop-spss/raw/master/data/exercisea4/exercisea4_data.sav)
- Exercise A5:
  [exercisea5_data.sav](https://github.com/CSCAR/workshop-spss/raw/master/data/exercisea5/exercisea5_data.sav)
- Final Project:
[cars_wave1.xls](https://github.com/CSCAR/workshop-spss/raw/master/data/finalproject/cars_wave1.xls),
[cars_wave2.xls](https://github.com/CSCAR/workshop-spss/raw/master/data/finalproject/cars_wave2.xls)
