
# Exercise A3 -- Methodology Choice Practice
==========================================

In the below questions first determine what the appropriate analysis
method is based on the variables of interest and carry out these methods
within SPSS.

**A. From ExerciseA3\_Data\_A**

1.  Is there a relationship between sex (gender) and job category
    (jobcat)?

2.  Is there a relationship between job category (jobcat) and minority
    status (minority)?

3.  Is there a relationship between job category (jobcat) and salary
    (salary)?

4.  Is there a relationship between experience (jobtime) and salary
    (salary)?

**B. From ExerciseA3\_Data\_B**

1.  Is there a relationship between general happiness (happy) and
    occupational prestige score (prestg80)?

2.  Is there a relationship between age (age) and occupational prestige
    score (prestg80)?

3.  Is there a relationship between general happiness (happy) and
    perception of life being exciting or dull (life)?

**Exercise A3 Hints! **

A1. Two Categorical VariablesClustered Bar Charts, Pearson Chi-Square
Crosstabs

A2. Two Categorical VariablesClustered Bar Charts, Pearson Chi-Square
Crosstabs

A3. Categorical DV (3+Groups) & Continuous DVOne Way ANOVA, Side-by-Side
Boxplot

A4. Two Continuous VariablesPearson Correlation Coefficient, Scatterplot

B1. Categorical DV (3+Groups) & Continuous DVOne Way ANOVA, Side-by-Side
Boxplot

B2. Two Continuous VariablesPearson Correlation Coefficient, Scatterplot

B3. Two Categorical VariablesClustered Bar Charts, Pearson Chi-Square
Crosstabs
